### ISSUE TITLE
Redesigned Homepage + New Copy

### ISSUE THREAD

**Issue by flavioriper** [estuary/marketing-site#188]
## Description
We decided to create a more professional-looking homepage. Our goal is to get higher conversion/engagement time metrics

## Work required

- [x] Updated Copy
- [x] Updated Design

## Figma / Designs
https://www.figma.com/file/qhXFvOJPqLgGsr9lsAPYbn/Estuary%3A-Product-Page?type=design&node-id=1402%3A4330&mode=design&t=azHJzVJR5dJa7A0Q-1

**Comment by altitude-lucas** [comment]
Sent to design for re-vamp with updated copy from the team

**Comment by altitude-lucas** [comment]
@Brenosalv the design is ready to go: https://www.figma.com/file/qhXFvOJPqLgGsr9lsAPYbn/Estuary%3A-Product-Page?type=design&node-id=3627%3A6071&mode=design&t=L0Racx1Yw6MYAiLQ-1

Please make this high-priority for this week
