### ISSUE TITLE
Breadcrumbs - Blog Pages

### ISSUE THREAD

**Issue by altitude-lucas** [estuary/marketing-site#264]
In an effort to ease site usability, I'm recommending that we add Breadcrumbs to the Blog pages, between the H1 + H2

**Comment by altitude-lucas** [comment]
![Image](https://github.com/estuary/marketing-site/assets/167227013/94cbbb3c-17b2-484e-afab-380fc03dd4e4)

@Brenosalv - From Design

**Comment by altitude-lucas** [comment]
@Brenosalv - I looked at the test site here, should be good to go on my end

**Comment by Brenosalv** [comment]
@altitude-lucas Yeah, just waiting Travis to approve the merge.
