### ISSUE TITLE
Breadcrumbs - Connectors

### ISSUE THREAD

**Issue by altitude-lucas** [estuary/marketing-site#265]
In an effort to ease site usability, I'm recommending that we add Breadcrumbs to the Connector pages, between the H1 + H2

**Comment by Brenosalv** [comment]
@altitude-lucas It needs design work yet, right? If so, we can add the ```needs design``` label to this issue.

**Comment by altitude-lucas** [comment]
![Image](https://github.com/estuary/marketing-site/assets/167227013/207a9ae5-d2e4-4def-a3c4-9c3ab126ff62)

@Brenosalv - from Design

**Comment by altitude-lucas** [comment]
@Brenosalv should be good to push here as well
