### ISSUE TITLE
Website Banner Update - Interaction with Header

### ISSUE THREAD

**Issue by altitude-lucas** [estuary/marketing-site#267]

**Comment by Brenosalv** [comment]
@altitude-lucas Could you provide more details about this issue?

**Comment by altitude-lucas** [comment]
@Brenosalv sure - the banner on the website overlaps the header, it should be above the header rather than sitting over top of it as it changes the design/spacing on the header bar

![Image](https://github.com/estuary/marketing-site/assets/167227013/f10bf17f-a8cf-4f3e-a76d-137dafad3ae9)
