### ISSUE TITLE
Flow Page - Pricing Update

### ISSUE THREAD

**Issue by altitude-lucas** [estuary/marketing-site#268]
I’m seeing cost per GB transferred at different prices on the site: $0.50/GB plus $0.14/hr (https://estuary.dev/vs-fivetran/), $1.00/GB plus $0.14/hr (https://estuary.dev/pricing/), $1.50/GB plus $0.14/hr (https://estuary.dev/vs-debezium/)

The correct version is the one you see on the main pricing page (https://estuary.dev/pricing/).

**Comment by altitude-lucas** [comment]
@Brenosalv wanted to flag this issue - it seems semi high-priority in my opinion

**Comment by Brenosalv** [comment]
@altitude-lucas thanks for creating the issue, Lucas. I'll work on it soon.

**Comment by Brenosalv** [comment]
@altitude-lucas Cool. So once I finish a task, I was thinking about pushing it to "Behavior Review" section as I did with this one, then you review and push it to "Done" if it's correct. If it's not correct, I push it to "In Progress". What do you think about?
