### ISSUE TITLE
Align website font to Sans-serif font

### ISSUE THREAD

**Issue by altitude-lucas** [estuary/marketing-site#280]
Currently the codebase is defaulted to Meriweather - we need to update this to Inter which is the font rendering on the headers

**Comment by Brenosalv** [comment]
The font-family is not being applied to some of the paragraphs of some of the blog posts. It's happening when the paragraphs come with span as a child:

```<p><span>Text</span></p>```

**Comment by Brenosalv** [comment]
@altitude-lucas Now we're using Inter sans-serif by default for the entire website. However, some blog posts use a different font for their text. To set the blog posts to have font Inter as the rest of the website, we would need to set the font as `Default` in Strapi:

![Image](https://github.com/user-attachments/assets/1a4c49de-1f7a-42c6-b911-5f716c78b1a4)

**Comment by Brenosalv** [comment]
@altitude-lucas Yes, but only the posts with a font other than the default.

**Comment by altitude-lucas** [comment]
Understood, how would we audit this?

**Comment by Brenosalv** [comment]
I can show you during the meeting and we can discuss about other possible solutions.
