### ISSUE TITLE
Calculator prices overflowing for high number of connectors

### ISSUE THREAD

**Issue by Brenosalv** [estuary/marketing-site#309]
**Bug**

- Calculator prices overflowing for high number of connectors.

**Expected**

- It should not overflow.

**Screenshots**
![image](https://github.com/estuary/marketing-site/assets/60396753/90a3226a-c2ff-4063-b43a-d2cb4f4bfc2d)

**Comment by altitude-lucas** [comment]
@Brenosalv moving this to high priority

**Comment by Brenosalv** [comment]
@altitude-lucas I'm thinking about limit the value with ellipsis for very high numbers. What do you think?

**Comment by altitude-lucas** [comment]
Let me check with the team first - I have a thought about this I want to run by Sales/Marketing
