### ISSUE TITLE
Homepage Adjustments - Number Styling

### ISSUE THREAD

**Issue by altitude-lucas** [estuary/marketing-site#318]
![Image](https://github.com/estuary/marketing-site/assets/167227013/69105f3f-995f-4785-8b75-f6be76de73ba)

![Image](https://github.com/estuary/marketing-site/assets/167227013/51fe6488-c1d8-40d0-9271-6bac5f471eb7)

![Image](https://github.com/estuary/marketing-site/assets/167227013/ae723185-7986-4ada-96f7-4f18604d3b28)

![Image](https://github.com/estuary/marketing-site/assets/167227013/995beab7-87e2-49f4-a0b6-94a440db5f52)

**Comment by Brenosalv** [comment]
@altitude-lucas, this issue was solved in PR [280](https://github.com/estuary/marketing-site/pull/414), when we changed the font.

**Comment by Brenosalv** [comment]
@altitude-lucas, we can close this issue since it was solved on PR [280](https://github.com/estuary/marketing-site/pull/414), when we changed the font.
