### ISSUE TITLE
Refine Mobile and Tablet version of overall site width

### ISSUE THREAD

**Issue by altitude-lucas** [estuary/marketing-site#347]
In a previous issue we implemented a max site width, however we need to adjust this to consider smaller screen sizes. Currently in Tablet and Mobile views, the left padding remains the same, it should grow smaller proportionately.

**Comment by Brenosalv** [comment]
@altitude-lucas Could we go over that again? Where did you notice the left padding not increasing proportionately? Do we have a screenshot of this?

**Comment by altitude-lucas** [comment]
@Brenosalv between 1200 and 1400px wide (very common screen size) the space to the left and right of the header becomes a problem. Then again between 1000 and 1200 the button disappears into the overflow. 

![Image](https://github.com/user-attachments/assets/ccb21154-1f5d-40d7-8ccd-6957bda53442)

**Comment by Brenosalv** [comment]
@altitude-lucas Okay, so what do you suggest as a solution? The number of elements in the header/navbar does not give us enough space. Possible solutions that come in my mind is either we remove one or two items, or we consider a horizontal padding much smaller than the default padding used by the rest of the website.

**Comment by Brenosalv** [comment]
@altitude-lucas Got it. The header should have a horizontal padding smaller than the default used by the sections.

**Comment by Brenosalv** [comment]
Closed with the PR: https://github.com/estuary/marketing-site/pull/409
