### ISSUE TITLE
New Customers Page

### ISSUE THREAD

**Issue by altitude-lucas** [estuary/marketing-site#351]
General idea : getting quotes from customers, champions of the product.

**Comment by danthelion** [comment]
should be a new page to hold all customer caste studies, similarly to: https://www.striim.com/customers

**Comment by danthelion** [comment]
design: https://www.figma.com/design/qhXFvOJPqLgGsr9lsAPYbn/Estuary%3A-Product-Page?node-id=10012-23707&t=Yb6oEEZ4MwauW4wG-1
