### ISSUE TITLE
Adjust "noreferrer" tags

### ISSUE THREAD

**Issue by altitude-lucas** [estuary/marketing-site#358]
Remove the rel="noreferrer" attribute from our internal links.

 It's likely causing our internal traffic to be misattributed as direct traffic in our analytics. This attribute is mainly ideal for external links, not internal ones.

Additionally, add an optional "nofollow" checkbox for external links: This would allow us to mark specific external links as nofollow when appropriate.

**Comment by Brenosalv** [comment]
There is no quick solution to add nofollow to random external links from blog posts in Strapi and does not make sense to post-process the links without a pattern.
