### ISSUE TITLE
Add e-mail submission to Integration/Connector page to improve conversion.

### ISSUE THREAD

**Issue by EstuaryRob** [estuary/marketing-site#388]
## Description

This is from the Estuary-site slack channel (now that I have GitHub access.)
Add an e-mail field to the left of the Get Started (or Try Now) button throughout the integration page. This is also a test to see if we can improve conversion rates in general by capturing an e-mail before they go through the registration process.

I've included a description and examples below.

Text above the Get Started button and text box:
"Enter your company e-mail to register"
Get Started (button)  Text field ("Email" written inside field like our own example)
The Contact Us button should move farther away to the right.

Examples:
On our own site, "register for the newsletter" at the bottom of the the home and product pages.
https://www.rudderstack.com/guides/how-to-load-data-from-postgresql-to-snowflake/

## Work required
-   [x] Add this to the hero section in the redesigned integration page.

## Figma / Designs
![Image](https://github.com/user-attachments/assets/95dee143-fb70-4b16-9033-a9af066775bd)

**Comment by EstuaryRob** [comment]
One last point on the e-mail submission that we will need to figure out.

The e-mail should alway be submitted. They may enter an e-mail that is not the same as their sign-in. The question is whether submitting this to the newsletter e-mail list is enough, and how this will work. Travis and others may have a good recommendation.

**Comment by Brenosalv** [comment]
@altitude-lucas Could you check if the email submission is working in the hero section of the integration page? Here is the preview URL: https://estuary-marketing--pr389-brenosalv-feature-33-25bopsjj.web.app/

**Comment by Brenosalv** [comment]
@altitude-lucas I think we can move this to done, right?

**Comment by altitude-lucas** [comment]
Yes, I closed this. Thank you
