### ISSUE TITLE
Menu Bug

### ISSUE THREAD

**Issue by altitude-lucas** [estuary/marketing-site#427]
Issue with header menu, when I open the submenu, and move my cursor toward the sub menu it disappears 

https://github.com/user-attachments/assets/ce524c8f-d085-4d5c-a891-004bd4136888

**Comment by Brenosalv** [comment]
@altitude-lucas I'm trying to reproduce here on Chrome and Safari but it's not happening. Which browser are you using? Are you testing the production/live version? Are you doing something different?

**Comment by altitude-lucas** [comment]
No longer able to replicate the issue
