### ISSUE TITLE
Deployment Options page

### ISSUE THREAD

**Issue by danthelion** [estuary/marketing-site#513]
## Description

New page for deployment options
[Estuary Flow Deployment Modes](https://docs.google.com/document/d/1zp6weHNsMqUVNey9Kz02CmPabSCT3befUX7H76g39tc/edit)

## Work required

-   [x] Create deployment options page.

## Figma / Designs

https://www.figma.com/design/qhXFvOJPqLgGsr9lsAPYbn/Estuary%3A-Product-Page?node-id=8661-24807&node-type=frame&t=xHXFeBBVtswEVbcu-0

**Comment by Brenosalv** [comment]
@danthelion Is it ready for development or still need design? Also, I don't have access to the doc from the description. I requested access.
