### ISSUE TITLE
Implement preview images for URLs

### ISSUE THREAD

**Issue by danthelion** [estuary/marketing-site#516]
![Image](https://github.com/user-attachments/assets/238fdc7c-1d07-4ca4-aa91-f63a8aa203cf)

**Comment by Brenosalv** [comment]
We need to fix the code - it's coming `undefined`:
![Image](https://github.com/user-attachments/assets/34e1979f-79b2-4af5-b9e8-fed0b49fbe39)
![Image](https://github.com/user-attachments/assets/fd52521e-33bd-4594-9bc0-1a23490a65fe)
