### ISSUE TITLE
New feature banner on main page

### ISSUE THREAD

**Issue by danthelion** [estuary/marketing-site#525]
Add new feature release banner to main page based on mockup by Polina. 

The banner should be clickable and be configurable where it redirects. The default content should be for the private deployment feature release and redirect should be to the new deployment modes page.

**Comment by Brenosalv** [comment]
I will leave to do this once we have the deployment options page done.

**Comment by danthelion** [comment]
re-usable component for any marketing site page (add to blog page as well and main to start with)
