### ISSUE TITLE
Deployment Modes section on main page

### ISSUE THREAD

**Issue by danthelion** [estuary/marketing-site#527]
Create a block on the main page that shows deployment modes. similarly to https://www.fivetran.com/ (scroll down)

**Comment by Brenosalv** [comment]
@danthelion Should we use the same text as well?
![Image](https://github.com/user-attachments/assets/87fcf9a8-46f3-48cf-944b-b42ef9348394)

**Comment by Brenosalv** [comment]
I will leave to do this once we have the deployment options page done.

**Comment by danthelion** [comment]
@Brenosalv: We have a design for this: https://www.figma.com/design/qhXFvOJPqLgGsr9lsAPYbn/Estuary%3A-Product-Page?t=HmFXqSDFdTgT5Hhp-0

**Comment by Brenosalv** [comment]
Closed with #541.
